### ISSUE TITLE
Add tags for matched terms in each report

### ISSUE THREAD

**Issue by geezhawk** [TID-Lab/aggie#216]
The Twitter API treats commas as logical ORs, so it will sometimes return a tweet that contains only a subset of the search terms specified by the user. But in some cases the user might be interested only in tweets that contain a combination of terms - eg "election" AND "fraud", not "election" OR "fraud." I suggest adding a series of tags after the text in the report content column with the matched terms so the user can see at a glance if the right combination of terms appear in a given tweet/FB post. I think something like the subject tags attached to a Stack Overflow post would be suitable here. If you're interested I'd be happy to build something and submit a PR, just lmk.

**Comment by pgarrison** [comment]
Thanks @geezhawk! Aggie should definitely have something like this. What is your use case? I would support a PR with the changes you propose, although perhaps we can be more ambitious, since we've been thinking about a similar feature that seems like it would address the same issue. Unfortunately it will probably be a few months before we can do much work on this feature, but I'm happy to give advice on implementation. We were thinking to

1. Support multiple twitter sources (each takes a list of keywords and does logical OR)
2. Each source can be given a list of tags, and the reports that it generates inherit the tags from the source that generated them

If the users added only one keyword per source, I think this would be the same as what you propose. However, this is a bit more complicated than what you propose, especially when we realize that a tweet could match multiple sources (e.g. one source say "A or B" and one says "B or C", or one source has "foo" and one has "foobar"). So we'll also have to

3. allow reports to have multiple sources, and make sure that things like filtering by source behave accordingly
4. make sure that each tweet only becomes one report, even if it matches multiple sources

I can give a lot more detail on how to implement this if you want to take this on. Also, whether you want to work on your proposal or this one, another important addition is to update the report filter to support tags. We just did this for the incidents table in 2.4.

**Comment by pgarrison** [comment]
Aha, this is a higher priority for us than I indicated. We're going to move forward with something close to what I outlined above in the next couple weeks. Maybe a good place to start is adding tags to sources. Tests for that would check that e.g. you can enter tags when creating/editing a source, and those tags show up in the list at `/sources`, and when a source creates reports the reports' tags should include their sources tags. I think @karthiksbhat started looking into this a little.

**Comment by geezhawk** [comment]
Thanks @pgarrison I'd be happy to add tags to sources, and once y'all get started on building the interface to add multiple sources I can pitch in. I'll get started on that this evening - do you guys have a Slack channel or something where I can message you if I have questions? I'm still familiarizing myself with the codebase here. Also what time zone are you in? @amandahmeng gave me the impression that you guys are traveling a lot.

As for my use case, I'm a developer at the AJC so we might be interested in using something like this for elections, hurricanes, or other big events. I'm bummed that we didn't get to it in time for this year's election but I'm sure we'll have opportunities to use it in the future.

**Comment by pgarrison** [comment]
Great, we'll add you to the slack channel. We're mostly in Macau (GMT+8). And feel free to ask for help -- there's a lot of old code in here.

**Comment by andresfib** [comment]
In #229 we added support for tags and several Twitter sources. So now reports gets the tags defined in their source. Not exactly what @geezhawk proposes but close enough.
