### ISSUE TITLE
Update backend & frontend dependencies

### ISSUE THREAD

**Issue by karpawich** [TID-Lab/aggie#294]
## Introduction

Before major development can resume on the Aggie repo, dependencies should be updated to their latest versions so that we avoid relying on outdated, unstable, or unsupported libraries and frameworks.

- **Node:** 0.10 to 12.16.3

**Comment by karpawich** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Upgrade modules/dependencies](https://trello.com/c/cBqAeHnx/13-upgrade-modules-dependencies)

**Comment by pgarrison** [comment]
Glad to see this is being prioritized; this looks like a solid plan! I tried to start this years ago and got overwhelmed. Here are some ideas to consider:
* The key reason it was hard is that some dependencies required node 0.10. Hopefully those can be replaced or upgraded.
* Update `devDependencies` first, along with the tests.
* Use ESLint as much as possible. The latest version of ESLint doesn't support Node 0.10, so you'll have to upgrade. For some issues, ESLint can auto-correct, which may save tons of time. Upgrade `.eslintrc` before touching the code.
* If upgrading all the way to v12 in one shot is too big, upgrade first to an intermediate version, then to v12. On the other hand, this might just be extra work.

**Comment by karpawich** [comment]
@pgarrison Thanks for the valuable input! Any guidance from old Aggie contributors who know their way around is very much appreciated. 

I haven't updated the Issue w/ my actual approach yet, but I definitely started with the tests! I deleted the `package.json` and `shrinkwrap.json` (old lockfile) and have just kept running the mocha tests to work one package at a time. Eventually I'll stop getting errors about missing dependencies, and then I'll do the more comprehensive refactor described above where I go one file at a time.

I'll have to get ESLint up and running **ASAP** now that you mention it. Right now I'm just trying to get rid of frozen/unsupported dependencies, but once when we shift to the file-by-file refactor I'll be sure to have it operational to tell us where the code is broken.

Thanks again 🥳

**Comment by limmabean** [comment]
It was a previous issue that was brought up on the Sassafras platform to update both MongoDB to 3.2 and Mongoose to v4. I'm commenting on it here so there is a record that we wanted to update them. 
This is because mongo 2.6 is depreciated and "I'd like to use the $lookup command introduced in mongo 3.2, which needs mongoose >= 4.3.0". "Mongo 3.2 also introduced the handy $sample. Also I think querying on timestamps got some convenient upgrades."

**Comment by karpawich** [comment]
@limmabean Thank you for bringing that up! I have already replaced Mongoose plugins with ones that support v5, but had not gotten to actually upgrading Mongoose itself.

I'll add a note! 👍

**Comment by limmabean** [comment]
Another issue that was brought up with production dependencies was this:
When running npm install --production it complains of two packages not being available
"gulp-jsoncombine": "1.0.3",
"merge-stream": "1.0.0"
They should either

be moved out of dev-dependencies and into dependencies
Remove test related tasks from npm install

Because this work is related (and probably going to be addressed as part of the process), I'm commenting it here.
